bus_route = {
    1: [
        {"title": "삼육대", "isStop": True},
        {"title": "삼육대 정문", "isStop": False},
        {"title": "태릉선수촌", "isStop": False},
        {"title": "태릉", "isStop": False},
        {"title": "서울여대, 육군사관학교", "isStop": False},
        {"title": "경춘선숲길", "isStop": False},
        {"title": "화랑대사거리", "isStop": False},
        {"title": "두산대림아파트", "isStop": False},
        {"title": "봉화산역", "isStop": False},
        {"title": "두산대림아파트", "isStop": False},
        {"title": "화랑대역", "isStop": True, "label": [1], "round": True},
        {"title": "화랑대사거리", "isStop": False},
        {"title": "경춘선숲길", "isStop": False},
        {"title": "서울여대, 육군사관학교", "isStop": False},
        {"title": "태릉", "isStop": False},
        {"title": "태릉선수촌", "isStop": False},
        {"title": "삼육대 정문", "isStop": False},
        {"title": "삼육대", "isStop": True},
    ],
    2: [
        {"title": "삼육대", "isStop": True},
        {"title": "삼육대 정문", "isStop": False},
        {"title": "담터교차로.담터고개", "isStop": False},
        {"title": "담터입구", "isStop": False},
        "미리내마을입구",
        {"title": "힐스테이트별내역.별내자이더스타", "isStop": False},
        {"title": "별내역2번출구", "isStop": True, "label": [3], "round": True},
        {"title": "힐스테이트별내역.별내자이더스타", "isStop": False},
        {"title": "미리내마을입구", "isStop": False},
        {"title": "담터입구", "isStop": False},
        {"title": "담터교차로.담터고개", "isStop": False},
        {"title": "삼육대 정문", "isStop": False},
        {"title": "삼육대", "isStop": True},
    ],
    3: [
        {"title": "삼육대", "isStop": True},
        {"title": "삼육대 정문", "isStop": False},
        {"title": "태릉선수촌", "isStop": False},
        {"title": "태릉", "isStop": False},
        {"title": "서울여대, 육군사관학교", "isStop": False},
        {"title": "경춘선숲길", "isStop": False},
        {"title": "화랑대사거리", "isStop": False},
        {"title": "화랑대역", "isStop": True, "label": [1]},
        {"title": "태릉입구역", "isStop": True, "label": [1, 2]},
        {"title": "월릉교", "isStop": False},
        {"title": "석계역", "isStop": True, "label": [0, 1], "round": True},
        {"title": "월릉교", "isStop": False},
        {"title": "태릉입구역", "isStop": True, "label": [1, 2]},
        {"title": "화랑대역", "isStop": True, "label": [1]},
        {"title": "화랑대사거리", "isStop": False},
        {"title": "경춘선숲길", "isStop": False},
        {"title": "서울여대, 육군사관학교", "isStop": False},
        {"title": "태릉", "isStop": False},
        {"title": "태릉선수촌", "isStop": False},
        {"title": "삼육대 정문", "isStop": False},
        {"title": "삼육대", "isStop": True},
    ],
}
